### ISSUE TITLE
Не отображается слайдер

### ISSUE THREAD

**Issue by Constantine-P** [ArtemDmitrenko/ad-slider#1]
В хроме:
![image](https://user-images.githubusercontent.com/18898493/129216232-ae41938d-d57d-474d-90db-942b86213874.png)

В фф:
![image](https://user-images.githubusercontent.com/18898493/129216276-c263c01b-9eda-4049-a216-48211a0b98e1.png)

**Comment by ArtemDmitrenko** [comment]
Странно, у меня ни в хроме, ни в фф нет проблем:
<img width="1425" alt="Снимок экрана 2021-08-18 в 23 05 52" src="https://user-images.githubusercontent.com/48836855/129965128-c0faa26b-2142-485f-988d-5aaf99ba7ef4.png">
<img width="1393" alt="Снимок экрана 2021-08-18 в 23 06 41" src="https://user-images.githubusercontent.com/48836855/129965149-4dd39b34-c0ee-44af-87ab-e76e3dc48e31.png">


> В хроме:
> ![image](https://user-images.githubusercontent.com/18898493/129216232-ae41938d-d57d-474d-90db-942b86213874.png)
> 
> В фф:
> ![image](https://user-images.githubusercontent.com/18898493/129216276-c263c01b-9eda-4049-a216-48211a0b98e1.png)

**Comment by Constantine-P** [comment]
Сорян, в хроме adblock свирепствует. В FF на ubuntu так, на винде норм. Если есть возможность, под линукс в ff тоже проверь / поправь.

**Comment by ArtemDmitrenko** [comment]
Не очень понимаю что для этого нужно сделать..до этого момента я думал, что ОС не влияет на отображение в браузере
