### ISSUE TITLE
Вью

### ISSUE THREAD

**Issue by Constantine-P** [ArtemDmitrenko/ad-slider#11]
![image](https://user-images.githubusercontent.com/18898493/136817767-357d5528-ce9e-41d0-9467-fac21040b330.png)
лучше перенести в соостветствующий класс. И надо исправить по бэм.

**Comment by ArtemDmitrenko** [comment]
> ![image](https://user-images.githubusercontent.com/18898493/136817767-357d5528-ce9e-41d0-9467-fac21040b330.png) лучше перенести в соостветствующий класс. И надо исправить по бэм.

Перенести в соответствующий класс не получается, так как здесь (во Вью) создается 2 инстанса класса HandlerView: handlerViewFrom и handlerView. И далее элементу $handler из инстанса handlerViewFrom я добавляю класс, которого соответсвенно не будет у элемента $handler в инстансе handlerView...
