### ISSUE TITLE
Инициализация слайдера

### ISSUE THREAD

**Issue by Everrest1** [ArtemDmitrenko/ad-slider#13]
Должна быть возможность инициализировать слайдер вызовом миксина, принимающего аргументами настройки

**Comment by ArtemDmitrenko** [comment]
> Не совсем понял зачем итерировать массив с настройками, если они не используются
> 
> ![image](https://user-images.githubusercontent.com/43137324/153627942-2b5ca9b5-11ed-4065-a3bd-3f871fd12cbf.png)

Здесь использовал итерацию только для того, отображалось заданное количество demo-slider на странице и не нужно было вручную прописывать

**Comment by ArtemDmitrenko** [comment]
Fixed here fd8774282bcd048f6170b54b87816c9d03ab7d5f
