### ISSUE TITLE
Именование файлов

### ISSUE THREAD

**Issue by Everrest1** [ArtemDmitrenko/ad-slider#16]
Имя файла с классом должно полностью соответствовать имени класса, который в нём объявлен

**Comment by ArtemDmitrenko** [comment]
Fixed here e2fce3885fc1dfd56b8d88859cd3633732a4f426

**Comment by Everrest1** [comment]
Это касается всех файлов с классами в проекте)

**Comment by ArtemDmitrenko** [comment]
> Это касается всех файлов с классами в проекте)

Исправил в прошлый раз, но git проигнорировал регистр. Поменял конфиг, исправил

**Comment by Everrest1** [comment]
Я бы ещё имена папок переименовал для поддержания общего стиля

![image](https://user-images.githubusercontent.com/43137324/156769353-7a86085c-28f0-4df5-89d5-60be4be81bf0.png)
