### ISSUE TITLE
Баги слайдера

### ISSUE THREAD

**Issue by Everrest1** [ArtemDmitrenko/ad-slider#18]
Надо обработать данный случай

![image](https://user-images.githubusercontent.com/43137324/155300321-00d9a036-3391-4f52-9f2e-3f77135e1c34.png)

Странное поведение при изменении ограничивающих значений

![2069e3b3-b3f9-4c7b-9984-c49927b6562b](https://user-images.githubusercontent.com/43137324/155300192-ff985ddd-5baa-4577-95aa-6212c0a91262.gif)

**Comment by ArtemDmitrenko** [comment]
Шкалу подправил. По поводу бага с изменением ограничивающих значений у меня вроде бы все нормально работает:

![Mar-02-2022 18-35-41](https://user-images.githubusercontent.com/48836855/156405998-71753892-ea64-4e4a-850c-d51661bed823.gif)

**Comment by Everrest1** [comment]
Попробуй повторить за мной, как на гифках

![d20b884b-323f-49ca-9d27-43df3822cd5b](https://user-images.githubusercontent.com/43137324/156770680-c40d1fb2-aa58-432b-9263-05af1ce99dc6.gif)

Почему значение "до" становится именно 80?

![6384fdd9-926b-45b9-a2c3-592e23f9ab60](https://user-images.githubusercontent.com/43137324/156771000-47b55689-9ef3-49f5-a6d7-3da73b2dba4f.gif)

При отключении диапазона плашка ломается

![264735cb-a6c7-4552-b6e7-2cd444dd66f9](https://user-images.githubusercontent.com/43137324/156771319-791e1fab-a6d3-492a-bb2d-df5bdba1d233.gif)

**Comment by Everrest1** [comment]
После переключения на диапазон в минимальном значении не получается перетащить ползунок

![9098e037-6ed3-4c15-a0cc-61507a17ec24](https://user-images.githubusercontent.com/43137324/157443706-d7a03d28-2f3c-4ece-9a9e-18fb923357e2.gif)

При переназначении минимального значения слайдер ломается

И при изменении полей значения иногда сбрасываются на предыдущие, а иногда нет

![de7fab80-5537-47bd-bfdc-8076e3594086](https://user-images.githubusercontent.com/43137324/157444322-45f223d9-3561-4e05-a93d-27781961398b.gif)

**Comment by Everrest1** [comment]
Иногда флаг "показать значение" не срабатывает

![8e09680e-2b18-4b21-9436-b37c1bac137b](https://user-images.githubusercontent.com/43137324/157444770-887630c1-c6aa-48ad-a646-f653dd36bfc5.gif)

**Comment by Everrest1** [comment]
Если какие-то значения передаваемые в инпут невалидны, то инпут должен сбрасываться после анфокуса

![f106a667-a77c-41f0-b63b-42c4fe6a3385](https://user-images.githubusercontent.com/43137324/158628228-3243906b-b323-449b-93ad-a9ea3ac85eb6.gif)
![216d2160-b678-4f14-9c68-14e241bb4a02](https://user-images.githubusercontent.com/43137324/158628416-f08f8c63-ae8a-418c-84a0-4dad63c69866.gif)

**Comment by Everrest1** [comment]
Сделай плиз инпуты числовым типом

![image](https://user-images.githubusercontent.com/43137324/162996702-9a20622e-9b0a-44d6-8784-03d76e1526c1.png)

**Comment by Everrest1** [comment]
Что-то совсем сломалось

![image](https://user-images.githubusercontent.com/43137324/164047137-b4889460-acb1-4243-b625-857acd687433.png)

**Comment by ArtemDmitrenko** [comment]
У меня на локалке и на gh-pages все ок. Если запускаешь у себя на локалке попробуй перед запуском удалить папку .parcel-cache
