### ISSUE TITLE
Работа слайдера

### ISSUE THREAD

**Issue by Constantine-P** [ArtemDmitrenko/ad-slider#2]
![image](https://user-images.githubusercontent.com/18898493/130026775-ea1ddb53-8ca8-4256-a34d-1d63488ae64a.png)
Может это фишка, но мне кажется странным. Получается можно установить значение не попадающее в шаг, и от него как от базового будет ходить ползунок. Мне кажется логично было бы, если бы значения всегда соответствовали шкале. То есть если я, например, ввожу "от" 13 то, значение округляется до ближайшего по шкале, то есть до 20.

**Comment by Constantine-P** [comment]
![2021-09-03_19-18](https://user-images.githubusercontent.com/18898493/132011543-f61940a1-64fa-4f18-bb3a-56c8f046c3a9.png)
Думаю тут значения на шкале должны быть  тоже 0 - 40 - 80 - 120

**Comment by Constantine-P** [comment]
![Peek 2021-09-03 19-24](https://user-images.githubusercontent.com/18898493/132012384-916e64e9-142a-4bea-92ab-089928849363.gif)
Тут значение в модели похоже сохраняется как 13, хотя на самом слайдере ползунок на 20

**Comment by ArtemDmitrenko** [comment]
> ![Peek 2021-09-03 19-24](https://user-images.githubusercontent.com/18898493/132012384-916e64e9-142a-4bea-92ab-089928849363.gif)
> Тут значение в модели похоже сохраняется как 13, хотя на самом слайдере ползунок на 20

Нет, когда ты при шаге 20 меняешь текущее значение на 13, то в модели это значение проходит валидацию и с учетом шага остается равным 20-ти. Просто когда после этого ты меняешь шаг на 1, то соответственно view обновляется на основе имеющихся на панели данных, а именно шага 1 и тек. значения 13, и уже после этого тек. значение в модели становится равным 13. Поэтому вроде бы все логично.

**Comment by Constantine-P** [comment]
![2021-09-10_22-44](https://user-images.githubusercontent.com/18898493/132888499-0ecfee91-dabd-4b0f-94b5-772cdd02f46f.png)
Поменял минимальное значение на -100.

**Comment by Constantine-P** [comment]
Если сначала перевести ползунок в конец:
![2021-09-16_18-54](https://user-images.githubusercontent.com/18898493/133615697-9c83abd7-3011-46bb-969c-855e7a495830.png)

**Comment by ArtemDmitrenko** [comment]
> Если сначала перевести ползунок в конец:
> ![2021-09-16_18-54](https://user-images.githubusercontent.com/18898493/133615697-9c83abd7-3011-46bb-969c-855e7a495830.png)

Можешь подробнее пояснить как получается такой баг?

**Comment by Constantine-P** [comment]
![Peek 2021-09-17 01-31](https://user-images.githubusercontent.com/18898493/133674545-eccb675f-8ed6-44fa-9e41-98052ed15a59.gif)

**Comment by ArtemDmitrenko** [comment]
Вроде делаю все абсолютно в такой же последовательности как ты, но у меня все о
![Sep-17-2021 22-17-18](https://user-images.githubusercontent.com/48836855/133842415-e8a155d5-c72d-45ba-b3a2-38321fc41224.gif)
к:

**Comment by ArtemDmitrenko** [comment]
Вроде делаю все абсолютно в такой же последовательности как ты, но у меня все ок
![Sep-17-2021 22-17-18](https://user-images.githubusercontent.com/48836855/133842540-23c6fe73-fa91-492b-82b0-6a26c9e2f296.gif)

**Comment by Constantine-P** [comment]
Попробуй не перетаскивать, а кликать по шкале
