### ISSUE TITLE
Посмотреть замечания по первому проекту и заюзать здесь

### ISSUE THREAD

**Issue by Constantine-P** [ArtemDmitrenko/ad-slider#4]
Уже было
![2021-09-03_19-42](https://user-images.githubusercontent.com/18898493/132014935-fd8d172a-a445-45f2-a19b-0ff037194f57.png)

**Comment by Constantine-P** [comment]
Приведение к boolean избыточно:
![2021-09-10_23-08](https://user-images.githubusercontent.com/18898493/132891413-77f4e19b-74fd-4398-8008-70b5a038a4d9.png)

Можно одной строкой заменить:
![2021-09-10_23-06](https://user-images.githubusercontent.com/18898493/132891145-73b709f1-d95d-4b4a-906c-2a6465b44b9c.png)

**Comment by Constantine-P** [comment]
![2021-09-16_19-36](https://user-images.githubusercontent.com/18898493/133622360-e0e76af9-1cf1-45e6-992f-8a89719180d9.png)
![2021-09-16_19-37](https://user-images.githubusercontent.com/18898493/133622366-f06875ab-10f8-45d8-afa2-0c1db76d5aa5.png)

На 309 строке число 3 похоже на магическое число

**Comment by Constantine-P** [comment]
См. предыдущий коммент. Не должно быть такого кода `if (1< 2) { return true }; returm false;`

**Comment by Constantine-P** [comment]
БЭМ
![image](https://user-images.githubusercontent.com/18898493/135644426-4cad64d6-6c5d-4ca3-97ab-e85c28bbcb0a.png)

**Comment by ArtemDmitrenko** [comment]
BEM naming fixed in this commit 
https://github.com/ArtemDmitrenko/ad-slider/commit/ef223c88f354f0944015bc5f58bd9009b814e2e0

**Comment by Constantine-P** [comment]
![image](https://user-images.githubusercontent.com/18898493/136662801-32338ab2-01fa-460a-be8f-b4da16c9a772.png)
camelCase - нельзя, kebab-case - можно

**Comment by Constantine-P** [comment]
![image](https://user-images.githubusercontent.com/18898493/136663017-ad560313-0641-44bb-8422-07b9bc4d8ccf.png)

**Comment by Constantine-P** [comment]
![image](https://user-images.githubusercontent.com/18898493/140950016-8ed09282-8da0-4d88-928e-5b3b953b988a.png)
