### ISSUE TITLE
Typescript, сборка

### ISSUE THREAD

**Issue by Constantine-P** [ArtemDmitrenko/ad-slider#8]
Есть места, где мне ideшка показывает ошибки в типах, например:
![2021-09-16_20-13](https://user-images.githubusercontent.com/18898493/133628032-2d40baab-a105-423a-a7e5-a989bcd5a0fb.png)
При этом сборка проходит нормально, т.е. компилятор ts в parcel не ругается. Даже вот так все собирается:
![2021-09-16_20-11](https://user-images.githubusercontent.com/18898493/133627699-7ebded87-012e-472b-9b48-8b4dc9206bd0.png)

Надо настроить сборщик, чтобы при ошибках не билдился с текстом, что все ок. Тут с парселем не подскажу, не использовал его.

**Comment by ArtemDmitrenko** [comment]
Исходя из документации парсель не выполняет проверку типов, и предлагает использовать tsc --noEmit:
<img width="1200" alt="Снимок экрана 2021-09-20 в 0 02 47" src="https://user-images.githubusercontent.com/48836855/134245692-bc70565b-86db-4a6b-be48-10cc8c857354.png">
Соответственно, я исправил большинство ошибок, но осталось 3, связанные с JQuery, пока не придумал как их решить буду благодарен если подскажешь

**Comment by ArtemDmitrenko** [comment]
> Исходя из документации парсель не выполняет проверку типов, и предлагает использовать tsc --noEmit:
> <img alt="Снимок экрана 2021-09-20 в 0 02 47" width="1200" src="https://user-images.githubusercontent.com/48836855/134245692-bc70565b-86db-4a6b-be48-10cc8c857354.png">
> Соответственно, я исправил большинство ошибок, но осталось 3, связанные с JQuery, пока не придумал как их решить буду благодарен если подскажешь



> Есть места, где мне ideшка показывает ошибки в типах, например:
> ![2021-09-16_20-13](https://user-images.githubusercontent.com/18898493/133628032-2d40baab-a105-423a-a7e5-a989bcd5a0fb.png)
> При этом сборка проходит нормально, т.е. компилятор ts в parcel не ругается. Даже вот так все собирается:
> ![2021-09-16_20-11](https://user-images.githubusercontent.com/18898493/133627699-7ebded87-012e-472b-9b48-8b4dc9206bd0.png)
> 
> Надо настроить сборщик, чтобы при ошибках не билдился с текстом, что все ок. Тут с парселем не подскажу, не использовал его.



> Исходя из документации парсель не выполняет проверку типов, и предлагает использовать tsc --noEmit:

> <img alt="Снимок экрана 2021-09-20 в 0 02 47" width="1200" src="https://user-images.githubusercontent.com/48836855/134245692-bc70565b-86db-4a6b-be48-10cc8c857354.png">

> Соответственно, я исправил большинство ошибок, но осталось 3, связанные с JQuery, пока не придумал как их решить буду благодарен если подскажешь

**Comment by ArtemDmitrenko** [comment]
> Есть места, где мне ideшка показывает ошибки в типах, например:
> ![2021-09-16_20-13](https://user-images.githubusercontent.com/18898493/133628032-2d40baab-a105-423a-a7e5-a989bcd5a0fb.png)
> При этом сборка проходит нормально, т.е. компилятор ts в parcel не ругается. Даже вот так все собирается:
> ![2021-09-16_20-11](https://user-images.githubusercontent.com/18898493/133627699-7ebded87-012e-472b-9b48-8b4dc9206bd0.png)
> 
> Надо настроить сборщик, чтобы при ошибках не билдился с текстом, что все ок. Тут с парселем не подскажу, не использовал его.

> Исходя из документации парсель не выполняет проверку типов, и предлагает использовать tsc --noEmit:

> <img alt="Снимок экрана 2021-09-20 в 0 02 47" width="1200" src="https://user-images.githubusercontent.com/48836855/134245692-bc70565b-86db-4a6b-be48-10cc8c857354.png">

> Соответственно, я исправил большинство ошибок, но осталось 3, связанные с JQuery, пока не придумал как их решить буду благодарен если подскажешь

**Comment by ArtemDmitrenko** [comment]
> Исходя из документации парсель не выполняет проверку типов, и предлагает использовать tsc --noEmit:

> <img alt="Снимок экрана 2021-09-20 в 0 02 47" width="1200" src="https://user-images.githubusercontent.com/48836855/134245692-bc70565b-86db-4a6b-be48-10cc8c857354.png">

> Соответственно, я исправил большинство ошибок, но осталось 3, связанные с JQuery, пока не придумал как их решить буду благодарен если подскажешь

**Comment by ArtemDmitrenko** [comment]
> Есть места, где мне ideшка показывает ошибки в типах, например:
> ![2021-09-16_20-13](https://user-images.githubusercontent.com/18898493/133628032-2d40baab-a105-423a-a7e5-a989bcd5a0fb.png)
> При этом сборка проходит нормально, т.е. компилятор ts в parcel не ругается. Даже вот так все собирается:
> ![2021-09-16_20-11](https://user-images.githubusercontent.com/18898493/133627699-7ebded87-012e-472b-9b48-8b4dc9206bd0.png)
> 
> Надо настроить сборщик, чтобы при ошибках не билдился с текстом, что все ок. Тут с парселем не подскажу, не использовал его.

Исходя из документации парсель не выполняет проверку типов, и предлагает использовать tsc --noEmit:

<img alt="Снимок экрана 2021-09-20 в 0 02 47" width="1200" src="https://user-images.githubusercontent.com/48836855/134245692-bc70565b-86db-4a6b-be48-10cc8c857354.png">

Соответственно, я исправил большинство ошибок, но осталось 3, связанные с JQuery, пока не придумал как их решить буду благодарен если подскажешь

**Comment by Constantine-P** [comment]
Попробуй вот это https://v2.parceljs.org/languages/typescript/#experimental-validator-plugin

**Comment by Constantine-P** [comment]
![image](https://user-images.githubusercontent.com/18898493/140944641-5959f851-ee97-435d-b44d-677d19c6f6f0.png)
По-моему это надо выпилить из репозитория. Эта папка в гитигноре, но почему-то в репозитории. Из-за этого кэша у меня не запускается проект

**Comment by Constantine-P** [comment]
![image](https://user-images.githubusercontent.com/18898493/140950793-fb0d5c51-53d5-4583-88d0-76196967f7e8.png)
![image](https://user-images.githubusercontent.com/18898493/140950845-f2c07897-585e-467f-872c-81a98930c339.png)

**Comment by Constantine-P** [comment]
![image](https://user-images.githubusercontent.com/18898493/140951168-b4f9b5e9-5c23-4bb3-914e-6ff13c3dfb3e.png)
Кастовать не надо, можно просто проверить на null

**Comment by ArtemDmitrenko** [comment]
https://github.com/ArtemDmitrenko/ad-slider/issues/8#issuecomment-964247067
По этой ошибке подскажи, пожалуйста, куда копать. Я исправил вроде тип возвращаемого значения, но ошибка все равно не уходит:
<img width="614" alt="Снимок экрана 2021-11-13 в 19 35 08" src="https://user-images.githubusercontent.com/48836855/141651860-6b4b1ac3-7ba7-4c79-a680-52e014b0f663.png">

**Comment by Constantine-P** [comment]
Сюда jquery.adslider.d.ts

**Comment by Constantine-P** [comment]
![image](https://user-images.githubusercontent.com/18898493/144607316-8d82e522-d5bf-4676-a944-178ea2f43d81.png)
